# ────────────────────────────────────────────
# SAM Configuration File for PRODUCTION Environment
# This file is specific for the production environment and should only be used in the "production" branch.
# ────────────────────────────────────────────

version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws-production"
s3_bucket = "aws-sam-cli-managed-production-samclisourcebucket-cgnbucket"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\", TodoTableName=\"todo-table-production\""
image_repositories = []
